module.exports = [
    {
        id: 1,
        name: 'Diego Fernandes',
        avatar: 'https://avatars2.githubusercontent.com/u/2254731?s=460&u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&v=4',
        whatsapp: 78998765432,
        bio: "Entusiasta das melhores tecnologias de química avançada. Apaixonado por explodir coisas em laboratório e por mudar a vida das pessoas através de experiências. Mais de 200.000 pessoas já passaram por uma das minhas explosões.",
        subject: 'Química',
        cost: 20,
        weekday: 1,
        time_from: 720,
        time_to: 1220,
    },
    {
        id: 2,
        name: 'Mayk Brito',
        avatar: 'https://avatars2.githubusercontent.com/u/6643122?s=460&u=1e9e1f04b76fb5374e6a041f5e41dce83f3b5d92&v=4',
        whatsapp: '7899887766',
        bio: 'Instrutor de Educação Física para iniciantes, minha missão de vida é levar saúde e contribuir para o crescimento de quem se interessar. Comecei a minha jornada profissional em 2001, quando meu pai me deu dois alteres de 32kg com a seguinte condição: "Aprenda a fazer dinheiro com isso!"',
        subject: 'Educação Física',
        cost: 40,
        weekday: 2,
        time_from: 120,
        time_to: 3220,
    },
    {
        id: 3,
        name: 'Tiago Luchtenberg',
        avatar: 'https://media-exp1.licdn.com/dms/image/C4E03AQHfarmcSLlWtA/profile-displayphoto-shrink_200_200/0?e=1601510400&v=beta&t=rh6nGIHnXucBXqJOZWs3_WSq6DdTaCPYNQph8XRzIE0',
        whatsapp: '7899887766',
        bio: 'As vezes não sei nem onde eu tô, mas consigo me localizar facilmente em qualquer lugar. Tenho memória fotográfica e nunca fico perdido. Eu ensino a galera como não se perder na vida, com lições geográficas simples pra você nunca mais precisar de mapa na sua bela vida. ',
        subject: 'Geografia',
        cost: 360,
        weekday: 3,
        time_from: 20,
        time_to: 4220,
    },
]